<?php

declare(strict_types=1);

$productCollectionProvider = $block->getData('activity_product_provider');
$products = $productCollectionProvider->getProducts();
?>
<a href="/landing/activity?activity=5447">
    <h3>With url query (gym) </h3>
</a>
<div style="display:flex; flex-wrap:wrap; gap:1rem;">
    <?php foreach ($products as $product) : ?>
        <a style="min-width:10rem; border:solid 1px rgba(0,0,0,.2);box-shadow:0 0 10px #ccc; padding:1rem;flex:1 1; border-radius:.5rem; color:black; display:flex; flex-direction:column; gap:1rem" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
            <?= $escaper->escapeHtml($product->getName()) ?>
            <span>
                SKU:
                <span>
                    <?= $escaper->escapeHtml($product->getSKU()) ?>
                </span>
            </span>
            <span>
                Price:
                <span>
                    <?= $escaper->escapeHtml("{$productCollectionProvider->getCurrencySymbol()}{$escaper->escapeHtml($product->getFinalPrice())}")?>
                </span>
            </span>
            <span>
                <img src="<?= $escaper->escapeURL($productCollectionProvider->getImageUrl($product, 'product_small_image'))?>"
                     alt="">
            </span>
            <span>
                Activites:
                <ul>
                    <?php if (is_array($product->getAttributeText('activity'))) : ?>
                        <?php foreach ($product->getAttributeText('activity') as $activity) : ?>
                            <li>
                                <?= $escaper->escapeHtml(__($activity)) ?>
                            </li>
                        <?php endforeach ?>
                    <?php else : ?>
                        <li>
                            <?= $escaper->escapeHtml(__($product->getAttributeText('activity'))) ?>
                        </li>
                    <?php endif ?>
                </ul>
            </span>
        </a>
    <?php endforeach ?>
</div>
